- id: nhsd-git-secrets
  name: NHSD Git Secrets
  description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
  entry: scripts/git-secrets-wrapper.sh
  language: script
  files: .*
  stages: [commit, merge-commit]
  pass_filenames: false